### ISSUE TITLE
Compilation error FirstWindow.java#L24

### ISSUE THREAD

**Issue by asentsov** [tkenaz/MobiDevTestJavaFX#1]
https://github.com/tkenaz/MobiDevTestJavaFX/blob/3711ea4c8fe6d701cf39de7df1fdf9d7fca638ae/src/sample/FirstWindow.java#L24

Patch to fix:

Index: src/sample/FirstWindow.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/sample/FirstWindow.java	(revision 3711ea4c8fe6d701cf39de7df1fdf9d7fca638ae)
+++ src/sample/FirstWindow.java	(date 1568886730122)
@@ -21,6 +21,6 @@
         window.setTitle(title);
         window.showAndWait();
 //TODO Pls help I got completely stuck here...
-        executor.schedule((() -> Platform.runLater(((Stage)window.getScene().getWindow()).close())), 3, TimeUnit.SECONDS);
+        executor.schedule((() -> Platform.runLater(()->((Stage)window.getScene().getWindow()).close())), 3, TimeUnit.SECONDS);
     }
 }

**Comment by tkenaz** [comment]
Alex, this one is set up, thank you for the help, still the task is not performed to the end. I have troubles with getting output text. 
As to the further logic, I would love to use postgres, and I've created db, etc. but it is useless as I am dumb as hell, apparently.

Pls take a look at what I've done. I will appreciate your feedback if any. And thank you for your time )))

**Comment by asentsov** [comment]
Well, you are moving ahead. Don`t waste your time for persistence level, you can create enum with a predefined list of users and its properties. That would be quite enough to validate over it for the pass and autologout value.
